[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/manifest"
  status = 200

[[redirects]]
  from = "/manifest.json"
  to = "/.netlify/functions/manifest"
  status = 200

[[redirects]]
  from = "/stream/*"
  to = "/.netlify/functions/stream"
  status = 200
